INSERT INTO t_car_motion_data_player (
  m_car_motion_data_id,
  m_suspension_position_RL,
  m_suspension_position_RR,
  m_suspension_position_FL,
  m_suspension_position_FR,
  m_suspension_velocity_RL,
  m_suspension_velocity_RR,
  m_suspension_velocity_FL,
  m_suspension_velocity_FR,
  m_suspension_acceleration_RL,
  m_suspension_acceleration_RR,
  m_suspension_acceleration_FL,
  m_suspension_acceleration_FR,
  m_wheel_speed_RL,
  m_wheel_speed_RR,
  m_wheel_speed_FL,
  m_wheel_speed_FR,
  m_wheel_slip_RL,
  m_wheel_slip_RR,
  m_wheel_slip_FL,
  m_wheel_slip_FR,
  m_local_velocity_x,
  m_local_velocity_Y,
  m_local_velocity_z,
  m_angular_velocity_X,
  m_angular_velocity_y,
  m_angular_velocity_z,
  m_angular_acceleration_x,
  m_angular_acceleration_y,
  m_angular_acceleration_z,
  m_front_wheels_angle
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
          ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
          ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
          ?)