CREATE TABLE t_state (
  id      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name    VARCHAR2(100) NOT NULL,
  fips    VARCHAR2(20) NOT NULL,
  CONSTRAINT t_state_pk PRIMARY KEY (id),
  CONSTRAINT t_state_unique_name UNIQUE (name),
  CONSTRAINT t_state_unique_fips UNIQUE (fips)
);

CREATE TABLE t_county (
  id      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name    VARCHAR2(100) NOT NULL,
  fips    VARCHAR2(20) NOT NULL,
  state_id NUMBER NOT NULL,
  CONSTRAINT t_county_unique_name UNIQUE (name),
  CONSTRAINT t_county_unique_fips UNIQUE (fips),
  CONSTRAINT t_county_fk FOREIGN KEY (state_id) REFERENCES t_state (id)
);