CREATE TABLE t_session_data (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  m_session_UID NUMBER NOT NULL,
  m_weather VARCHAR2(100),
  m_track_temperature NUMBER,
  m_air_temperature NUMBER,
  m_total_laps NUMBER,
  m_track_length NUMBER,
  m_session_type VARCHAR2(100),
  m_track_id VARCHAR2(100),
  m_formula VARCHAR2(100),
  m_session_time_left NUMBER,
  m_session_duration NUMBER,
  m_pit_speed_limit NUMBER,
  m_game_paused NUMBER,
  m_is_spectating NUMBER,
  m_spectator_car_index NUMBER,
  m_sli_pro_native_support NUMBER,
  m_car_safety_status VARCHAR(100),
  m_network_game VARCHAR(100),
  CONSTRAINT t_session_data PRIMARY KEY (id)
);

CREATE TABLE t_marshal_zone (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  m_session_data_id NUMBER,
  m_zone_start NUMBER,
  m_zone_flag VARCHAR(100),
  CONSTRAINT t_marshal_zone_pk PRIMARY KEY (id),
  CONSTRAINT t_session_data_fk FOREIGN KEY (m_session_data_id) REFERENCES t_session_data (id)
);


CREATE TABLE t_weather_forecast_samples (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  m_session_data_id NUMBER,
  m_session_type VARCHAR(100),
  m_time_offset NUMBER,
  m_weather VARCHAR(100),
  m_track_temperature NUMBER,
  m_air_temperature NUMBER,
  CONSTRAINT t_weather_forecast_samples_pk PRIMARY KEY (id),
  CONSTRAINT t_session_data_weather_fk FOREIGN KEY (m_session_data_id) REFERENCES t_session_data (id)
);