INSERT INTO t_session_data (
  m_session_UID,
  m_weather,
  m_track_temperature,
  m_air_temperature,
  m_total_laps,
  m_track_length,
  m_session_type,
  m_track_id,
  m_formula,
  m_session_time_left,
  m_session_duration,
  m_pit_speed_limit,
  m_game_paused,
  m_is_spectating,
  m_spectator_car_index,
  m_sli_pro_native_support,
  m_car_safety_status,
  m_network_game
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)