INSERT INTO t_car_status_data (
  m_packet_id NUMBER,
  m_traction_control NUMBER,
  m_anti_lock_brakes NUMBER,
  m_fuel_mix VARCHAR2(100),
  m_front_brake_bias NUMBER,
  m_pit_limiter_status NUMBER,
  m_fuel_in_tank NUMBER,
  m_fuel_capacity NUMBER,
  m_fuel_remaining_laps NUMBER,
  m_max_rpm NUMBER,
  m_idel_rpm NUMBER,
  m_max_gears NUMBER,
  m_drs_allowed VARCHAR2(100),
  m_tyres_wear_RL NUMBER,
  m_tyres_wear_RR NUMBER,
  m_tyres_wear_FL NUMBER,
  m_tyres_wear_FR NUMBER,
  m_actual_tyre_compound VARCHAR2(100),
  m_visual_tyre_compound VARCHAR2(100),
  m_tyres_age_laps NUMBER,
  m_tyres_damage_RL NUMBER,
  m_tyres_damage_RR NUMBER,
  m_tyres_damage_FL NUMBER,
  m_tyres_damage_FR NUMBER,
  m_front_left_wing_damage NUMBER,
  m_front_right_wing_damage NUMBER,
  m_rear_wing_damage NUMBER,
  m_drs_fault VARCHAR2(100),
  m_engine_damage NUMBER,
  m_gear_box_damage NUMBER,
  m_vehicle_fia_flags VARCHAR2(100),
  m_ers_store_energy NUMBER,
  m_ers_deploy_mode NUMBER,
  m_ers_harvested_this_lap_MGUK NUMBER,
  m_ers_harvested_this_lap_MGUH NUMBER,
  m_ers_deployed_this_lap NUMBER,
) VALUES (
?,?,?,?,?,?,?,?,?,?,
?,?,?,?,?,?,?,?,?,?,
?,?,?,?,?,?,?,?,?,?,
?,?,?,?,?,?,?)